### ISSUE TITLE
I need to manually tab before each furigana/kanji... Help!

### ISSUE THREAD

**Issue by drewkiimon** [obynio/anki-japanese-furigana#32]
Hey y'all. I've been using this for a few days now, and I have to continuously use spaces before my Kanji, otherwise the Furigana things all the preceding text before the kanji needs to have the furigana above it.

How can I fix this? I see other people get it to work very well.

**Comment by ahlec** [comment]
Would you be able to post an example sentence? One sentence that produces the bad results (because it doesn't have the spaces), and then how you need to fix that sentence to get the results you want? Also, including a picture of the bad results so we can visualize it better (and/or pasting in the generated markdown/HTML)?

**Comment by RawToast** [comment]
This is a pet peeve of mine with this plugin, it inputs the braced furigana incorrectly.

For example, given the following sentence:

`天気はいいから散歩しましょう`

This plugin generates:

`天気[てんき]はいいから散歩[さんぽ]しましょう`

The correct format would be:

`天気[てんき]はいいから 散歩[さんぽ]しましょう`

Without the space before 散歩 the furigana will be spread across all the preceding characters

**Comment by obynio** [comment]
This issue was fixed and released in 1.4.6 🫡
